name: Build and deploy

on:
  push:
    branches:
      - main

env:
  DEPLOYMENT_NAME: warehousems


jobs:
  setup-build-publish:
      name: Setup build and setup-build-publish
      runs-on: ubuntu-latest
      steps:
        - run: echo "Build started "
        - name: Checkout repository
          uses: actions/checkout@v3
        - run: echo "Project repository has been clonde to runnner(ubuntu)"



     #create .env
        -
          name: Create env
          uses: "finnp/create-file-action@master"
          env:
            FILE_NAME: ".env"
            FILE_DATA: ${{ secrets.ENV_FILE }}

         #login to docker hub
        -
         name: Login to Docker Hub
         uses: docker/login-action@v2
         with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.TOKEN }}