name: Build and deploy

on:
  push:
    branches:
      - main

env:
  DEPLOYMENT_NAME: warehousems
  PROJECT_ID: ${{ secrets.GKA_PROJECT }}
  GKE_CLUSTER: cluster-isini
  GKE_ZONE: us-central1-c


jobs:
  setup-build-publish:
      name: Setup build and setup-build-publish
      runs-on: ubuntu-latest
      steps:
        - run: echo "Build started "
        - name: Checkout repository
          uses: actions/checkout@v3
        - run: echo "Project repository has been clonde to runnner(ubuntu)"



     #create .env
        -
          name: Create env
          uses: "finnp/create-file-action@master"
          env:
            FILE_NAME: ".env"
            FILE_DATA: ${{ secrets.ENV_FILE }}

         #login to docker hub
        -
         name: Login to Docker Hub
         uses: docker/login-action@v2
         with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.TOKEN }}

#BULD AND PUSH TO DCOCKER HUB

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        - name: Build and push
          uses: docker/build-push-action@v3
          with:
           context: .
           file: ./Dockerfile
           push: true
           tags: ${{ secrets.USERNAME }}/${{env.DEPLOYMENT_NAME}}:${{ github.sha }}

  deploy:
    needs: setup-build-publish
    name: deploy application
    runs-on: ubuntu-latest

    steps:
      - run: echo "Deplyment started"
      #Checkout application to deploy
      - name: Checkout repository
        uses: actions/checkout@v3
      #setup google clod auth
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
      # Setup gcloud CLI
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      # Get the GKE credentials so we can deploy to the cluster
      - run: |-
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"